### ISSUE TITLE
Comparison with `simple8b`

### ISSUE THREAD

**Issue by ccollie** [mwlon/quantile-compression#52]
Have you had a look at `simple8b` for comparison ?

**Comment by mwlon** [comment]
Looks like that's a new project using a FastPFor-like technique (I'll note it only has 1 release and that was 2 years ago). Parquet uses something similar under the hood, so I expect its compression ratio will be about the same, and you can look at those comparators.

If you're not satisfied with that, I encourage you to run your own comparisons.
