### ISSUE TITLE
C++ API

### ISSUE THREAD

**Issue by alphanso** [mwlon/quantile-compression#53]
Hi,

I have timeseries data set comprising of (int16_t, char, double, int32_t and int64_t). int64_t is timestamp in nanoseconds. We are planning to migrate to zstd as that seemed to be the best choice. I wanted to try Qcompress also. Is this production ready for large data (multiple TBs of read and write everyday)? Also, application is in C++ so is corresponding library available?

**Comment by mwlon** [comment]
@alphanso 

> Is this production ready for large data (multiple TBs of read and write everyday)?

Yes. The file format and its stability are well-tested, and the library is in use. Its performance for both decompression and compression is similar to zstd, but with higher compression ratio. The file format is chunked so you can put effectively unlimited data in (though I'm sure you'll have your own constraints around how big you want each file).

> Also, application is in C++ so is corresponding library available?

No, but Rust<->C++ interop is pretty good, so [it's easy to set up](https://bitboom.github.io/2020-11-04/calling-rust-from-cpp). If you make a C++ wrapper library, please open source it for others to use!
