### ISSUE TITLE
Wrapped Format Help

### ISSUE THREAD

**Issue by ccollie** [mwlon/quantile-compression#62]
I have a use-case for wrapped formats, and I'd like some help, since the example is not clear to me.

I have a structure like the following
```rust
#[derive(Default, Debug, Clone, PartialEq)]
pub struct Timeseries {
    pub metric_name: MetricName,
    pub values: Vec<f64>,
    pub timestamps: Arc<Vec<i64>>, //Arc used vs Rc since Rc is !Send
}
``` 

In certain cases, I have a `Vec<Timeseries>` which cover exactly the same timestamp range (note the `Arc`), and I'd like to serialize it as efficiently as possible. In practice, I'd like to serialize the timestamps once (delta level 2), then iteratively compress each `value` chunk.

Any pointers ?

**Comment by mwlon** [comment]
Good example - I'm going to assume some things about your use case (correct me if wrong):

* You have <16M data points per time series file
* You want the ability to seek to a specific time and and decompress it specifically

I'd imagine you would do this by interleaving the timestamps with each series. Your format would look like this in order:

* Your file-level header and such
* Timestamp q_compress header and chunk meta
* Series 0 header and chunk meta ... Series n-1 header and chunk meta
* Your data page 0 meta (including min and max timestamp, count, and compressed body sizes, allowing seeking)
* Timestamp data page 0
* Series 0 data page 0 ... Series n-1 data page 0
...
* Your data page m-1 meta
* Timestamp data page m-1
* Series 0 data page m-1 ... Series n-1 data page m-1

This interleaves all the data and stores each timestamp just once. Would this solve your problem?

**Comment by ccollie** [comment]
Sounds like it would work...

**Comment by mwlon** [comment]
I'll probably add an example in the docs soonish, but until then, I think the API plus the description above should be clear enough:
[compressor](https://docs.rs/q_compress/0.11.3/q_compress/wrapped/struct.Compressor.html)
[decompressor](https://docs.rs/q_compress/0.11.3/q_compress/wrapped/struct.Decompressor.html)

**Comment by ccollie** [comment]
> I just added a [wrapped time series example](https://github.com/mwlon/quantile-compression/blob/main/q_compress/examples/wrapped_time_series.rs), so closing this.

Nice ! Exactly what i need !
